# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
neck_joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: neck_joint1
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 
neck_joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: neck_joint2
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 
neck_joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: neck_joint3
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 
head_joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: head_joint
  pid: {p: 0.0, i: 0.0, d: 0.0} #200 1 1 
eye_joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: eye_joint1
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 
eye_joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: eye_joint2
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 
eye_joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: eye_joint3
  pid: {p: 0.0, i: 0.0, d: 0.0} #300 1 1 



