# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: neck
  joint_model_group_pose: initial_orientation
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - neck_joint1
    - neck_joint2
    - neck_joint3
    - head_joint
    - eye_joint1
    - eye_joint2
    - eye_joint3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: neck_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - neck_joint1
      - neck_joint2
      - neck_joint3
  - name: head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      head_joint
  - name: eye_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - eye_joint1
      - eye_joint2
      - eye_joint3